# Generated by Django 6.0.7 on 2026-09-29 17:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='household',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddConstraint(
            model_name='householdmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'owner')), fields=('household',), name='unique_household_owner'),
        ),
    ]
