# Generated by Django 6.0.7 on 2026-09-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_household_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='currency',
            field=models.CharField(choices=[('CZK', 'Czech koruna'), ('EUR', 'Euro'), ('USD', 'US dollar')], default='CZK', max_length=3),
        ),
    ]
