# Generated by Django 6.0.7 on 2026-10-07 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_household_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='currency',
            field=models.CharField(choices=[('CZK', 'Czech koruna'), ('EUR', 'Euro'), ('USD', 'US dollar'), ('RUB', 'Russian ruble')], default='CZK', max_length=3),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='currency',
            field=models.CharField(choices=[('CZK', 'Czech koruna'), ('EUR', 'Euro'), ('USD', 'US dollar'), ('RUB', 'Russian ruble')], default='CZK', max_length=3),
        ),
    ]
