# Generated by Django 6.0.7 on 2026-09-13 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_goalautomaticsaving'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalSavingTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal')], default='deposit', max_length=20)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('automatic_saving', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='goals.goalautomaticsaving')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saving_transactions', to='goals.financialgoal')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
