# Generated by Django 6.0.7 on 2026-10-06 18:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(choices=[('CZK', 'Czech koruna'), ('EUR', 'Euro'), ('USD', 'US dollar')], max_length=3, verbose_name='Базовая валюта')),
                ('target_currency', models.CharField(choices=[('CZK', 'Czech koruna'), ('EUR', 'Euro'), ('USD', 'US dollar')], max_length=3, verbose_name='Целевая валюта')),
                ('rate', models.DecimalField(decimal_places=10, max_digits=20, validators=[django.core.validators.MinValueValidator(1e-10)], verbose_name='Курс')),
                ('date', models.DateField(verbose_name='Дата курса')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Курс валюты',
                'verbose_name_plural': 'Курсы валют',
                'ordering': ['-date', 'base_currency', 'target_currency'],
                'constraints': [models.UniqueConstraint(fields=('base_currency', 'target_currency', 'date'), name='unique_exchange_rate_per_day'), models.CheckConstraint(condition=models.Q(('base_currency', models.F('target_currency')), _negated=True), name='different_exchange_rate_currencies')],
            },
        ),
    ]
