# Generated by Django 6.0.7 on 2026-10-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_alter_exchangerate_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='base_currency',
            field=models.CharField(choices=[('CZK', 'Czech koruna'), ('EUR', 'Euro'), ('USD', 'US dollar'), ('RUB', 'Russian ruble')], max_length=3, verbose_name='Базовая валюта'),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='target_currency',
            field=models.CharField(choices=[('CZK', 'Czech koruna'), ('EUR', 'Euro'), ('USD', 'US dollar'), ('RUB', 'Russian ruble')], max_length=3, verbose_name='Целевая валюта'),
        ),
    ]
