# Generated by Django 6.0.7 on 2026-09-06 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='goals.financialgoal', verbose_name='Финансовая цель'),
        ),
    ]
