# Generated by Django 6.0.7 on 2026-10-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_expense_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='currency',
            field=models.CharField(choices=[('CZK', 'Czech koruna'), ('EUR', 'Euro'), ('USD', 'US dollar'), ('RUB', 'Russian ruble')], default='CZK', max_length=3, verbose_name='Валюта'),
        ),
    ]
